# Generated by Django 5.0.7 on 2024-11-23 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transferencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivo_de_transferencia', to='transferencias.motivo'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfiere', to=settings.AUTH_USER_MODEL),
        ),
    ]
