# Generated by Django 5.0.7 on 2024-11-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='default.png', upload_to='fotos_perfil/'),
        ),
    ]
